name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build_android:
    name: Build release APK for Android
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    - name: setup jdk
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        
    - name: Make Gradle executable
      run: chmod +x ./gradlew
      
    - name: Build Release APK
      run: ./gradlew :androidApp:assembleRelease
      
    - name: Upload iosApp artifact
      uses: actions/upload-artifact@v3
      with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
  
  build_ios:
    name: Build iOS .app for Simulator
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./iosApp
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
           java-version: '17'
           distribution: 'oracle'
           
      - name: Xcodebuild Action
        uses: sersoft-gmbh/xcodebuild-action@v2.0.1
        with:
          workspace: iosApp/iosApp.xcworkspace
          scheme: iosApp
          sdk: iphonesimulator
          derived-data-path: ./output
          action: build
          
      - name: Zip iosApp
        uses: vimtor/action-zip@v1
        with:
          files: output/Build/Products/Debug-iphonesimulator/iosApp.app
          dest: iosApp.app.zip
          
      - name: Upload iosApp artifact
        uses: actions/upload-artifact@v3
        with:
          name: iosApp.app.zip
          path: iosApp.app.zip
          
  release:
    name: Release Android and iOS builds
    needs: [build_android, build_ios]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/download-artifact@v3
        with:
          name: iosApp.app.zip
          
      - uses: actions/download-artifact@v3
        with:
          name: app-release.apk
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          
      - name: Upload iOS app
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: iosApp.app.zip
          asset_name: iosApp.app.zip
          asset_content_type: application/zip
          
      - name: Upload Android app
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
    
    
      
